//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace MyPress.Client.ServiceMyPress {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data", Namespace="http://schemas.datacontract.org/2004/07/MyPress.Web")]
    public partial class Data : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<MyPress.Client.ServiceMyPress.Bing> BingField;
        
        private string EmailField;
        
        private string LoginField;
        
        private string PassField;
        
        private System.Collections.ObjectModel.ObservableCollection<MyPress.Client.ServiceMyPress.Rubriki> RubrikiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<MyPress.Client.ServiceMyPress.Bing> Bing {
            get {
                return this.BingField;
            }
            set {
                if ((object.ReferenceEquals(this.BingField, value) != true)) {
                    this.BingField = value;
                    this.RaisePropertyChanged("Bing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<MyPress.Client.ServiceMyPress.Rubriki> Rubriki {
            get {
                return this.RubrikiField;
            }
            set {
                if ((object.ReferenceEquals(this.RubrikiField, value) != true)) {
                    this.RubrikiField = value;
                    this.RaisePropertyChanged("Rubriki");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bing", Namespace="http://schemas.datacontract.org/2004/07/MyPress.Web")]
    public partial class Bing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescriptionField;
        
        private string SentAnalysField;
        
        private string TitleField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SentAnalys {
            get {
                return this.SentAnalysField;
            }
            set {
                if ((object.ReferenceEquals(this.SentAnalysField, value) != true)) {
                    this.SentAnalysField = value;
                    this.RaisePropertyChanged("SentAnalys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rubriki", Namespace="http://schemas.datacontract.org/2004/07/MyPress.Web")]
    public partial class Rubriki : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<MyPress.Client.ServiceMyPress.Bing> BingField;
        
        private long CollField;
        
        private System.DateTime DateCreateField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<MyPress.Client.ServiceMyPress.Bing> Bing {
            get {
                return this.BingField;
            }
            set {
                if ((object.ReferenceEquals(this.BingField, value) != true)) {
                    this.BingField = value;
                    this.RaisePropertyChanged("Bing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Coll {
            get {
                return this.CollField;
            }
            set {
                if ((this.CollField.Equals(value) != true)) {
                    this.CollField = value;
                    this.RaisePropertyChanged("Coll");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreate {
            get {
                return this.DateCreateField;
            }
            set {
                if ((this.DateCreateField.Equals(value) != true)) {
                    this.DateCreateField = value;
                    this.RaisePropertyChanged("DateCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorList", Namespace="http://schemas.datacontract.org/2004/07/MyPress.Web")]
    public enum ErrorList : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succes = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DublicateName = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DublicateEmail = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccesPassword = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailedPass = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailNull = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMyPress.IMyPressService")]
    public interface IMyPressService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyPressService/QueryToBing", ReplyAction="http://tempuri.org/IMyPressService/QueryToBingResponse")]
        System.IAsyncResult BeginQueryToBing(string query, MyPress.Client.ServiceMyPress.Data data, string market, int countQuery, string nameRub, System.AsyncCallback callback, object asyncState);
        
        void EndQueryToBing(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyPressService/AddUser", ReplyAction="http://tempuri.org/IMyPressService/AddUserResponse")]
        System.IAsyncResult BeginAddUser(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState);
        
        void EndAddUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyPressService/RestorePass", ReplyAction="http://tempuri.org/IMyPressService/RestorePassResponse")]
        System.IAsyncResult BeginRestorePass(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState);
        
        MyPress.Client.ServiceMyPress.ErrorList EndRestorePass(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyPressService/CheckUser", ReplyAction="http://tempuri.org/IMyPressService/CheckUserResponse")]
        System.IAsyncResult BeginCheckUser(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState);
        
        MyPress.Client.ServiceMyPress.ErrorList EndCheckUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyPressService/CheckUserLogin", ReplyAction="http://tempuri.org/IMyPressService/CheckUserLoginResponse")]
        System.IAsyncResult BeginCheckUserLogin(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState);
        
        MyPress.Client.ServiceMyPress.ErrorList EndCheckUserLogin(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyPressServiceChannel : MyPress.Client.ServiceMyPress.IMyPressService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestorePassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RestorePassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MyPress.Client.ServiceMyPress.ErrorList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MyPress.Client.ServiceMyPress.ErrorList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CheckUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MyPress.Client.ServiceMyPress.ErrorList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MyPress.Client.ServiceMyPress.ErrorList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckUserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CheckUserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MyPress.Client.ServiceMyPress.ErrorList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MyPress.Client.ServiceMyPress.ErrorList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyPressServiceClient : System.ServiceModel.ClientBase<MyPress.Client.ServiceMyPress.IMyPressService>, MyPress.Client.ServiceMyPress.IMyPressService {
        
        private BeginOperationDelegate onBeginQueryToBingDelegate;
        
        private EndOperationDelegate onEndQueryToBingDelegate;
        
        private System.Threading.SendOrPostCallback onQueryToBingCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddUserDelegate;
        
        private EndOperationDelegate onEndAddUserDelegate;
        
        private System.Threading.SendOrPostCallback onAddUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginRestorePassDelegate;
        
        private EndOperationDelegate onEndRestorePassDelegate;
        
        private System.Threading.SendOrPostCallback onRestorePassCompletedDelegate;
        
        private BeginOperationDelegate onBeginCheckUserDelegate;
        
        private EndOperationDelegate onEndCheckUserDelegate;
        
        private System.Threading.SendOrPostCallback onCheckUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginCheckUserLoginDelegate;
        
        private EndOperationDelegate onEndCheckUserLoginDelegate;
        
        private System.Threading.SendOrPostCallback onCheckUserLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public MyPressServiceClient() {
        }
        
        public MyPressServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyPressServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyPressServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyPressServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Не удалось установить CookieContainer. Убедитесь, что привязка содержит HttpCooki" +
                            "eContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> QueryToBingCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddUserCompleted;
        
        public event System.EventHandler<RestorePassCompletedEventArgs> RestorePassCompleted;
        
        public event System.EventHandler<CheckUserCompletedEventArgs> CheckUserCompleted;
        
        public event System.EventHandler<CheckUserLoginCompletedEventArgs> CheckUserLoginCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyPress.Client.ServiceMyPress.IMyPressService.BeginQueryToBing(string query, MyPress.Client.ServiceMyPress.Data data, string market, int countQuery, string nameRub, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQueryToBing(query, data, market, countQuery, nameRub, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MyPress.Client.ServiceMyPress.IMyPressService.EndQueryToBing(System.IAsyncResult result) {
            base.Channel.EndQueryToBing(result);
        }
        
        private System.IAsyncResult OnBeginQueryToBing(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            MyPress.Client.ServiceMyPress.Data data = ((MyPress.Client.ServiceMyPress.Data)(inValues[1]));
            string market = ((string)(inValues[2]));
            int countQuery = ((int)(inValues[3]));
            string nameRub = ((string)(inValues[4]));
            return ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).BeginQueryToBing(query, data, market, countQuery, nameRub, callback, asyncState);
        }
        
        private object[] OnEndQueryToBing(System.IAsyncResult result) {
            ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).EndQueryToBing(result);
            return null;
        }
        
        private void OnQueryToBingCompleted(object state) {
            if ((this.QueryToBingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QueryToBingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QueryToBingAsync(string query, MyPress.Client.ServiceMyPress.Data data, string market, int countQuery, string nameRub) {
            this.QueryToBingAsync(query, data, market, countQuery, nameRub, null);
        }
        
        public void QueryToBingAsync(string query, MyPress.Client.ServiceMyPress.Data data, string market, int countQuery, string nameRub, object userState) {
            if ((this.onBeginQueryToBingDelegate == null)) {
                this.onBeginQueryToBingDelegate = new BeginOperationDelegate(this.OnBeginQueryToBing);
            }
            if ((this.onEndQueryToBingDelegate == null)) {
                this.onEndQueryToBingDelegate = new EndOperationDelegate(this.OnEndQueryToBing);
            }
            if ((this.onQueryToBingCompletedDelegate == null)) {
                this.onQueryToBingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQueryToBingCompleted);
            }
            base.InvokeAsync(this.onBeginQueryToBingDelegate, new object[] {
                        query,
                        data,
                        market,
                        countQuery,
                        nameRub}, this.onEndQueryToBingDelegate, this.onQueryToBingCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyPress.Client.ServiceMyPress.IMyPressService.BeginAddUser(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddUser(data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MyPress.Client.ServiceMyPress.IMyPressService.EndAddUser(System.IAsyncResult result) {
            base.Channel.EndAddUser(result);
        }
        
        private System.IAsyncResult OnBeginAddUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MyPress.Client.ServiceMyPress.Data data = ((MyPress.Client.ServiceMyPress.Data)(inValues[0]));
            return ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).BeginAddUser(data, callback, asyncState);
        }
        
        private object[] OnEndAddUser(System.IAsyncResult result) {
            ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).EndAddUser(result);
            return null;
        }
        
        private void OnAddUserCompleted(object state) {
            if ((this.AddUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddUserAsync(MyPress.Client.ServiceMyPress.Data data) {
            this.AddUserAsync(data, null);
        }
        
        public void AddUserAsync(MyPress.Client.ServiceMyPress.Data data, object userState) {
            if ((this.onBeginAddUserDelegate == null)) {
                this.onBeginAddUserDelegate = new BeginOperationDelegate(this.OnBeginAddUser);
            }
            if ((this.onEndAddUserDelegate == null)) {
                this.onEndAddUserDelegate = new EndOperationDelegate(this.OnEndAddUser);
            }
            if ((this.onAddUserCompletedDelegate == null)) {
                this.onAddUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddUserCompleted);
            }
            base.InvokeAsync(this.onBeginAddUserDelegate, new object[] {
                        data}, this.onEndAddUserDelegate, this.onAddUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyPress.Client.ServiceMyPress.IMyPressService.BeginRestorePass(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRestorePass(data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPress.Client.ServiceMyPress.ErrorList MyPress.Client.ServiceMyPress.IMyPressService.EndRestorePass(System.IAsyncResult result) {
            return base.Channel.EndRestorePass(result);
        }
        
        private System.IAsyncResult OnBeginRestorePass(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MyPress.Client.ServiceMyPress.Data data = ((MyPress.Client.ServiceMyPress.Data)(inValues[0]));
            return ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).BeginRestorePass(data, callback, asyncState);
        }
        
        private object[] OnEndRestorePass(System.IAsyncResult result) {
            MyPress.Client.ServiceMyPress.ErrorList retVal = ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).EndRestorePass(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRestorePassCompleted(object state) {
            if ((this.RestorePassCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RestorePassCompleted(this, new RestorePassCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RestorePassAsync(MyPress.Client.ServiceMyPress.Data data) {
            this.RestorePassAsync(data, null);
        }
        
        public void RestorePassAsync(MyPress.Client.ServiceMyPress.Data data, object userState) {
            if ((this.onBeginRestorePassDelegate == null)) {
                this.onBeginRestorePassDelegate = new BeginOperationDelegate(this.OnBeginRestorePass);
            }
            if ((this.onEndRestorePassDelegate == null)) {
                this.onEndRestorePassDelegate = new EndOperationDelegate(this.OnEndRestorePass);
            }
            if ((this.onRestorePassCompletedDelegate == null)) {
                this.onRestorePassCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRestorePassCompleted);
            }
            base.InvokeAsync(this.onBeginRestorePassDelegate, new object[] {
                        data}, this.onEndRestorePassDelegate, this.onRestorePassCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyPress.Client.ServiceMyPress.IMyPressService.BeginCheckUser(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCheckUser(data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPress.Client.ServiceMyPress.ErrorList MyPress.Client.ServiceMyPress.IMyPressService.EndCheckUser(System.IAsyncResult result) {
            return base.Channel.EndCheckUser(result);
        }
        
        private System.IAsyncResult OnBeginCheckUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MyPress.Client.ServiceMyPress.Data data = ((MyPress.Client.ServiceMyPress.Data)(inValues[0]));
            return ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).BeginCheckUser(data, callback, asyncState);
        }
        
        private object[] OnEndCheckUser(System.IAsyncResult result) {
            MyPress.Client.ServiceMyPress.ErrorList retVal = ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).EndCheckUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCheckUserCompleted(object state) {
            if ((this.CheckUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CheckUserCompleted(this, new CheckUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CheckUserAsync(MyPress.Client.ServiceMyPress.Data data) {
            this.CheckUserAsync(data, null);
        }
        
        public void CheckUserAsync(MyPress.Client.ServiceMyPress.Data data, object userState) {
            if ((this.onBeginCheckUserDelegate == null)) {
                this.onBeginCheckUserDelegate = new BeginOperationDelegate(this.OnBeginCheckUser);
            }
            if ((this.onEndCheckUserDelegate == null)) {
                this.onEndCheckUserDelegate = new EndOperationDelegate(this.OnEndCheckUser);
            }
            if ((this.onCheckUserCompletedDelegate == null)) {
                this.onCheckUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckUserCompleted);
            }
            base.InvokeAsync(this.onBeginCheckUserDelegate, new object[] {
                        data}, this.onEndCheckUserDelegate, this.onCheckUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyPress.Client.ServiceMyPress.IMyPressService.BeginCheckUserLogin(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCheckUserLogin(data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPress.Client.ServiceMyPress.ErrorList MyPress.Client.ServiceMyPress.IMyPressService.EndCheckUserLogin(System.IAsyncResult result) {
            return base.Channel.EndCheckUserLogin(result);
        }
        
        private System.IAsyncResult OnBeginCheckUserLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MyPress.Client.ServiceMyPress.Data data = ((MyPress.Client.ServiceMyPress.Data)(inValues[0]));
            return ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).BeginCheckUserLogin(data, callback, asyncState);
        }
        
        private object[] OnEndCheckUserLogin(System.IAsyncResult result) {
            MyPress.Client.ServiceMyPress.ErrorList retVal = ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).EndCheckUserLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCheckUserLoginCompleted(object state) {
            if ((this.CheckUserLoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CheckUserLoginCompleted(this, new CheckUserLoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CheckUserLoginAsync(MyPress.Client.ServiceMyPress.Data data) {
            this.CheckUserLoginAsync(data, null);
        }
        
        public void CheckUserLoginAsync(MyPress.Client.ServiceMyPress.Data data, object userState) {
            if ((this.onBeginCheckUserLoginDelegate == null)) {
                this.onBeginCheckUserLoginDelegate = new BeginOperationDelegate(this.OnBeginCheckUserLogin);
            }
            if ((this.onEndCheckUserLoginDelegate == null)) {
                this.onEndCheckUserLoginDelegate = new EndOperationDelegate(this.OnEndCheckUserLogin);
            }
            if ((this.onCheckUserLoginCompletedDelegate == null)) {
                this.onCheckUserLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckUserLoginCompleted);
            }
            base.InvokeAsync(this.onBeginCheckUserLoginDelegate, new object[] {
                        data}, this.onEndCheckUserLoginDelegate, this.onCheckUserLoginCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MyPress.Client.ServiceMyPress.IMyPressService CreateChannel() {
            return new MyPressServiceClientChannel(this);
        }
        
        private class MyPressServiceClientChannel : ChannelBase<MyPress.Client.ServiceMyPress.IMyPressService>, MyPress.Client.ServiceMyPress.IMyPressService {
            
            public MyPressServiceClientChannel(System.ServiceModel.ClientBase<MyPress.Client.ServiceMyPress.IMyPressService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginQueryToBing(string query, MyPress.Client.ServiceMyPress.Data data, string market, int countQuery, string nameRub, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = query;
                _args[1] = data;
                _args[2] = market;
                _args[3] = countQuery;
                _args[4] = nameRub;
                System.IAsyncResult _result = base.BeginInvoke("QueryToBing", _args, callback, asyncState);
                return _result;
            }
            
            public void EndQueryToBing(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("QueryToBing", _args, result);
            }
            
            public System.IAsyncResult BeginAddUser(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = data;
                System.IAsyncResult _result = base.BeginInvoke("AddUser", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddUser", _args, result);
            }
            
            public System.IAsyncResult BeginRestorePass(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = data;
                System.IAsyncResult _result = base.BeginInvoke("RestorePass", _args, callback, asyncState);
                return _result;
            }
            
            public MyPress.Client.ServiceMyPress.ErrorList EndRestorePass(System.IAsyncResult result) {
                object[] _args = new object[0];
                MyPress.Client.ServiceMyPress.ErrorList _result = ((MyPress.Client.ServiceMyPress.ErrorList)(base.EndInvoke("RestorePass", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCheckUser(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = data;
                System.IAsyncResult _result = base.BeginInvoke("CheckUser", _args, callback, asyncState);
                return _result;
            }
            
            public MyPress.Client.ServiceMyPress.ErrorList EndCheckUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                MyPress.Client.ServiceMyPress.ErrorList _result = ((MyPress.Client.ServiceMyPress.ErrorList)(base.EndInvoke("CheckUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCheckUserLogin(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = data;
                System.IAsyncResult _result = base.BeginInvoke("CheckUserLogin", _args, callback, asyncState);
                return _result;
            }
            
            public MyPress.Client.ServiceMyPress.ErrorList EndCheckUserLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                MyPress.Client.ServiceMyPress.ErrorList _result = ((MyPress.Client.ServiceMyPress.ErrorList)(base.EndInvoke("CheckUserLogin", _args, result)));
                return _result;
            }
        }
    }
}
