//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace MyPress.Client.ServiceMyPress {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data", Namespace="http://schemas.datacontract.org/2004/07/MyPress.Web")]
    public partial class Data : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<MyPress.Client.ServiceMyPress.Bing> BingField;
        
        private string EmailField;
        
        private string LoginField;
        
        private string PassField;
        
        private string RepPassField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<MyPress.Client.ServiceMyPress.Bing> Bing {
            get {
                return this.BingField;
            }
            set {
                if ((object.ReferenceEquals(this.BingField, value) != true)) {
                    this.BingField = value;
                    this.RaisePropertyChanged("Bing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepPass {
            get {
                return this.RepPassField;
            }
            set {
                if ((object.ReferenceEquals(this.RepPassField, value) != true)) {
                    this.RepPassField = value;
                    this.RaisePropertyChanged("RepPass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bing", Namespace="http://schemas.datacontract.org/2004/07/MyPress.Web")]
    public partial class Bing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescriptionField;
        
        private string SentAnalysField;
        
        private string TitleField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SentAnalys {
            get {
                return this.SentAnalysField;
            }
            set {
                if ((object.ReferenceEquals(this.SentAnalysField, value) != true)) {
                    this.SentAnalysField = value;
                    this.RaisePropertyChanged("SentAnalys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorList", Namespace="http://schemas.datacontract.org/2004/07/MyPress.Web")]
    public enum ErrorList : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succes = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DublicateName = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DublicateEmail = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMyPress.IMyPressService")]
    public interface IMyPressService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyPressService/QueryToBing", ReplyAction="http://tempuri.org/IMyPressService/QueryToBingResponse")]
        System.IAsyncResult BeginQueryToBing(string query, MyPress.Client.ServiceMyPress.Data data, string market, int countQuery, System.AsyncCallback callback, object asyncState);
        
        void EndQueryToBing(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyPressService/AddUser", ReplyAction="http://tempuri.org/IMyPressService/AddUserResponse")]
        System.IAsyncResult BeginAddUser(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState);
        
        MyPress.Client.ServiceMyPress.ErrorList EndAddUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyPressService/EnterUser", ReplyAction="http://tempuri.org/IMyPressService/EnterUserResponse")]
        System.IAsyncResult BeginEnterUser(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState);
        
        void EndEnterUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyPressService/RestorePass", ReplyAction="http://tempuri.org/IMyPressService/RestorePassResponse")]
        System.IAsyncResult BeginRestorePass(System.AsyncCallback callback, object asyncState);
        
        void EndRestorePass(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyPressServiceChannel : MyPress.Client.ServiceMyPress.IMyPressService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MyPress.Client.ServiceMyPress.ErrorList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MyPress.Client.ServiceMyPress.ErrorList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyPressServiceClient : System.ServiceModel.ClientBase<MyPress.Client.ServiceMyPress.IMyPressService>, MyPress.Client.ServiceMyPress.IMyPressService {
        
        private BeginOperationDelegate onBeginQueryToBingDelegate;
        
        private EndOperationDelegate onEndQueryToBingDelegate;
        
        private System.Threading.SendOrPostCallback onQueryToBingCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddUserDelegate;
        
        private EndOperationDelegate onEndAddUserDelegate;
        
        private System.Threading.SendOrPostCallback onAddUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginEnterUserDelegate;
        
        private EndOperationDelegate onEndEnterUserDelegate;
        
        private System.Threading.SendOrPostCallback onEnterUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginRestorePassDelegate;
        
        private EndOperationDelegate onEndRestorePassDelegate;
        
        private System.Threading.SendOrPostCallback onRestorePassCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public MyPressServiceClient() {
        }
        
        public MyPressServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyPressServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyPressServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyPressServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Не удалось установить CookieContainer. Убедитесь, что привязка содержит HttpCooki" +
                            "eContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> QueryToBingCompleted;
        
        public event System.EventHandler<AddUserCompletedEventArgs> AddUserCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EnterUserCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RestorePassCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyPress.Client.ServiceMyPress.IMyPressService.BeginQueryToBing(string query, MyPress.Client.ServiceMyPress.Data data, string market, int countQuery, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQueryToBing(query, data, market, countQuery, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MyPress.Client.ServiceMyPress.IMyPressService.EndQueryToBing(System.IAsyncResult result) {
            base.Channel.EndQueryToBing(result);
        }
        
        private System.IAsyncResult OnBeginQueryToBing(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            MyPress.Client.ServiceMyPress.Data data = ((MyPress.Client.ServiceMyPress.Data)(inValues[1]));
            string market = ((string)(inValues[2]));
            int countQuery = ((int)(inValues[3]));
            return ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).BeginQueryToBing(query, data, market, countQuery, callback, asyncState);
        }
        
        private object[] OnEndQueryToBing(System.IAsyncResult result) {
            ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).EndQueryToBing(result);
            return null;
        }
        
        private void OnQueryToBingCompleted(object state) {
            if ((this.QueryToBingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QueryToBingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QueryToBingAsync(string query, MyPress.Client.ServiceMyPress.Data data, string market, int countQuery) {
            this.QueryToBingAsync(query, data, market, countQuery, null);
        }
        
        public void QueryToBingAsync(string query, MyPress.Client.ServiceMyPress.Data data, string market, int countQuery, object userState) {
            if ((this.onBeginQueryToBingDelegate == null)) {
                this.onBeginQueryToBingDelegate = new BeginOperationDelegate(this.OnBeginQueryToBing);
            }
            if ((this.onEndQueryToBingDelegate == null)) {
                this.onEndQueryToBingDelegate = new EndOperationDelegate(this.OnEndQueryToBing);
            }
            if ((this.onQueryToBingCompletedDelegate == null)) {
                this.onQueryToBingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQueryToBingCompleted);
            }
            base.InvokeAsync(this.onBeginQueryToBingDelegate, new object[] {
                        query,
                        data,
                        market,
                        countQuery}, this.onEndQueryToBingDelegate, this.onQueryToBingCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyPress.Client.ServiceMyPress.IMyPressService.BeginAddUser(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddUser(data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPress.Client.ServiceMyPress.ErrorList MyPress.Client.ServiceMyPress.IMyPressService.EndAddUser(System.IAsyncResult result) {
            return base.Channel.EndAddUser(result);
        }
        
        private System.IAsyncResult OnBeginAddUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MyPress.Client.ServiceMyPress.Data data = ((MyPress.Client.ServiceMyPress.Data)(inValues[0]));
            return ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).BeginAddUser(data, callback, asyncState);
        }
        
        private object[] OnEndAddUser(System.IAsyncResult result) {
            MyPress.Client.ServiceMyPress.ErrorList retVal = ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).EndAddUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddUserCompleted(object state) {
            if ((this.AddUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddUserCompleted(this, new AddUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddUserAsync(MyPress.Client.ServiceMyPress.Data data) {
            this.AddUserAsync(data, null);
        }
        
        public void AddUserAsync(MyPress.Client.ServiceMyPress.Data data, object userState) {
            if ((this.onBeginAddUserDelegate == null)) {
                this.onBeginAddUserDelegate = new BeginOperationDelegate(this.OnBeginAddUser);
            }
            if ((this.onEndAddUserDelegate == null)) {
                this.onEndAddUserDelegate = new EndOperationDelegate(this.OnEndAddUser);
            }
            if ((this.onAddUserCompletedDelegate == null)) {
                this.onAddUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddUserCompleted);
            }
            base.InvokeAsync(this.onBeginAddUserDelegate, new object[] {
                        data}, this.onEndAddUserDelegate, this.onAddUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyPress.Client.ServiceMyPress.IMyPressService.BeginEnterUser(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEnterUser(data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MyPress.Client.ServiceMyPress.IMyPressService.EndEnterUser(System.IAsyncResult result) {
            base.Channel.EndEnterUser(result);
        }
        
        private System.IAsyncResult OnBeginEnterUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MyPress.Client.ServiceMyPress.Data data = ((MyPress.Client.ServiceMyPress.Data)(inValues[0]));
            return ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).BeginEnterUser(data, callback, asyncState);
        }
        
        private object[] OnEndEnterUser(System.IAsyncResult result) {
            ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).EndEnterUser(result);
            return null;
        }
        
        private void OnEnterUserCompleted(object state) {
            if ((this.EnterUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EnterUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EnterUserAsync(MyPress.Client.ServiceMyPress.Data data) {
            this.EnterUserAsync(data, null);
        }
        
        public void EnterUserAsync(MyPress.Client.ServiceMyPress.Data data, object userState) {
            if ((this.onBeginEnterUserDelegate == null)) {
                this.onBeginEnterUserDelegate = new BeginOperationDelegate(this.OnBeginEnterUser);
            }
            if ((this.onEndEnterUserDelegate == null)) {
                this.onEndEnterUserDelegate = new EndOperationDelegate(this.OnEndEnterUser);
            }
            if ((this.onEnterUserCompletedDelegate == null)) {
                this.onEnterUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEnterUserCompleted);
            }
            base.InvokeAsync(this.onBeginEnterUserDelegate, new object[] {
                        data}, this.onEndEnterUserDelegate, this.onEnterUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyPress.Client.ServiceMyPress.IMyPressService.BeginRestorePass(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRestorePass(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MyPress.Client.ServiceMyPress.IMyPressService.EndRestorePass(System.IAsyncResult result) {
            base.Channel.EndRestorePass(result);
        }
        
        private System.IAsyncResult OnBeginRestorePass(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).BeginRestorePass(callback, asyncState);
        }
        
        private object[] OnEndRestorePass(System.IAsyncResult result) {
            ((MyPress.Client.ServiceMyPress.IMyPressService)(this)).EndRestorePass(result);
            return null;
        }
        
        private void OnRestorePassCompleted(object state) {
            if ((this.RestorePassCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RestorePassCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RestorePassAsync() {
            this.RestorePassAsync(null);
        }
        
        public void RestorePassAsync(object userState) {
            if ((this.onBeginRestorePassDelegate == null)) {
                this.onBeginRestorePassDelegate = new BeginOperationDelegate(this.OnBeginRestorePass);
            }
            if ((this.onEndRestorePassDelegate == null)) {
                this.onEndRestorePassDelegate = new EndOperationDelegate(this.OnEndRestorePass);
            }
            if ((this.onRestorePassCompletedDelegate == null)) {
                this.onRestorePassCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRestorePassCompleted);
            }
            base.InvokeAsync(this.onBeginRestorePassDelegate, null, this.onEndRestorePassDelegate, this.onRestorePassCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MyPress.Client.ServiceMyPress.IMyPressService CreateChannel() {
            return new MyPressServiceClientChannel(this);
        }
        
        private class MyPressServiceClientChannel : ChannelBase<MyPress.Client.ServiceMyPress.IMyPressService>, MyPress.Client.ServiceMyPress.IMyPressService {
            
            public MyPressServiceClientChannel(System.ServiceModel.ClientBase<MyPress.Client.ServiceMyPress.IMyPressService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginQueryToBing(string query, MyPress.Client.ServiceMyPress.Data data, string market, int countQuery, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = query;
                _args[1] = data;
                _args[2] = market;
                _args[3] = countQuery;
                System.IAsyncResult _result = base.BeginInvoke("QueryToBing", _args, callback, asyncState);
                return _result;
            }
            
            public void EndQueryToBing(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("QueryToBing", _args, result);
            }
            
            public System.IAsyncResult BeginAddUser(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = data;
                System.IAsyncResult _result = base.BeginInvoke("AddUser", _args, callback, asyncState);
                return _result;
            }
            
            public MyPress.Client.ServiceMyPress.ErrorList EndAddUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                MyPress.Client.ServiceMyPress.ErrorList _result = ((MyPress.Client.ServiceMyPress.ErrorList)(base.EndInvoke("AddUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEnterUser(MyPress.Client.ServiceMyPress.Data data, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = data;
                System.IAsyncResult _result = base.BeginInvoke("EnterUser", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEnterUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EnterUser", _args, result);
            }
            
            public System.IAsyncResult BeginRestorePass(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("RestorePass", _args, callback, asyncState);
                return _result;
            }
            
            public void EndRestorePass(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("RestorePass", _args, result);
            }
        }
    }
}
