//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPress.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsKz_kz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsKz_kz() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPress.Client.Resources.StringsKz-kz", typeof(StringsKz_kz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Казахский язын здесь.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каким образом ваше имя должно отображаться в приложении.
        /// </summary>
        public static string FriendlyNameDescription {
            get {
                return ResourceManager.GetString("FriendlyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Понятное имя.
        /// </summary>
        public static string FriendlyNameLabel {
            get {
                return ResourceManager.GetString("FriendlyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение пароля.
        /// </summary>
        public static string PasswordConfirmationLabel {
            get {
                return ResourceManager.GetString("PasswordConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должен иметь длину 7 символов и содержать хотя бы один специальный символ, такой как @ или #.
        /// </summary>
        public static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ на секретный вопрос.
        /// </summary>
        public static string SecurityAnswerLabel {
            get {
                return ResourceManager.GetString("SecurityAnswerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Секретный вопрос.
        /// </summary>
        public static string SecurityQuestionLabel {
            get {
                return ResourceManager.GetString("SecurityQuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя.
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ на секретный вопрос не может быть длиннее 128 символов.
        /// </summary>
        public static string ValidationErrorBadAnswerLength {
            get {
                return ResourceManager.GetString("ValidationErrorBadAnswerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Понятное имя не может быть длиннее 255 символов..
        /// </summary>
        public static string ValidationErrorBadFriendlyNameLength {
            get {
                return ResourceManager.GetString("ValidationErrorBadFriendlyNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должен иметь длину от 7 до 50 символов.
        /// </summary>
        public static string ValidationErrorBadPasswordLength {
            get {
                return ResourceManager.GetString("ValidationErrorBadPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должен содержать хотя бы один специальный символ, такой как @ или #.
        /// </summary>
        public static string ValidationErrorBadPasswordStrength {
            get {
                return ResourceManager.GetString("ValidationErrorBadPasswordStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя должно иметь длину от 4 до 255 символов.
        /// </summary>
        public static string ValidationErrorBadUserNameLength {
            get {
                return ResourceManager.GetString("ValidationErrorBadUserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый адрес электронной почты. Он должен быть указан в формате пользователь@компания.ru.
        /// </summary>
        public static string ValidationErrorInvalidEmail {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое имя пользователя. Оно должно содержать только алфавитно-цифровые символы.
        /// </summary>
        public static string ValidationErrorInvalidUserName {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не совпадают.
        /// </summary>
        public static string ValidationErrorPasswordConfirmationMismatch {
            get {
                return ResourceManager.GetString("ValidationErrorPasswordConfirmationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это поле является обязательным.
        /// </summary>
        public static string ValidationErrorRequiredField {
            get {
                return ResourceManager.GetString("ValidationErrorRequiredField", resourceCulture);
            }
        }
    }
}
